#!/usr/bin/env Rscript

write_expression_assignment <- function(con, name, path) {
  expr <- parse(file = path, keep.source = FALSE)
  lines <- escape_non_ascii(capture.output(dput(expr)))
  writeLines(sprintf("%s <- ", name), con = con, sep = "")
  writeLines(lines, con = con)
  writeLines("", con = con)
}

escape_non_ascii <- function(lines) {
  escaped_lines <- vapply(
    enc2utf8(lines),
    function(line) {
      code_points <- utf8ToInt(line)
      escaped <- vapply(
        code_points,
        function(code_point) {
          if (code_point <= 127L) {
            intToUtf8(code_point)
          } else if (code_point <= 65535L) {
            sprintf("\\\\u%04X", code_point)
          } else {
            sprintf("\\\\U%08X", code_point)
          }
        },
        character(1),
        USE.NAMES = FALSE
      )
      paste0(escaped, collapse = "")
    },
    character(1),
    USE.NAMES = FALSE
  )
  sub("[[:space:]]+$", "", escaped_lines)
}

resolve_script_path <- function() {
  source_frame <- tryCatch(sys.frame(1L)$ofile, error = function(...) NULL)
  if (!is.null(source_frame) && nzchar(source_frame)) {
    return(normalizePath(source_frame, winslash = "/", mustWork = TRUE))
  }

  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) > 0L) {
    return(normalizePath(sub("^--file=", "", file_arg[[1L]]), winslash = "/", mustWork = TRUE))
  }

  stop("Unable to resolve the path to tools/generate_runtime_registry.R.", call. = FALSE)
}

repo_root <- normalizePath(file.path(dirname(resolve_script_path()), ".."), winslash = "/", mustWork = TRUE)

runtime_root <- file.path(repo_root, "tools", "runtime_source", "ndm_runtime")
run_api_path <- file.path(runtime_root, "SetupEnv", "Analysis2_api.R")
multidisease_driver_path <- file.path(runtime_root, "SetupEnv", "Analysis2_legacy_multidisease_driver.R")
output_path <- file.path(repo_root, "R", "runtime_registry_generated.R")

runtime_files <- c(
  "SetupEnv/SuperLModel_helperFxns.R",
  "SetupEnv/SuperLModel_MasterImports.R",
  "SetupData/SuperLModel_CalibrateML.R",
  "SetupData/SuperLModel_DataGenerator_Sim.R",
  "SetupData/SuperLModel_DataGenerator_Real.R",
  "SetupData/MultiDiseaseRuns/SuperL_UniversalDataReader.R",
  "ModelDefiners/SuperLModel_BuildML.R",
  "ModelDefiners/SuperLModel_BackboneTransformer.R",
  "ModelDefiners/SuperLModel_ParseDynamicODE.R",
  "ModelTrainers/SuperLModel_TrainDefine.R",
  "ModelTrainers/SuperLModel_TrainDo.R",
  "ResultsGet/SuperLModel_GetAnalytics.R",
  "ResultsGet/SuperLModel_GetAnalytics_Real.R",
  "ResultsGet/SuperLModel_GetAnalytics_Sim.R",
  "ResultsAnalyze/SuperLModel_GenFigs.R",
  "ResultsAnalyze/SuperLModel_GenFigs_RealPreprocess.R",
  "ResultsAnalyze/SuperLModel_GenFigs_GenInputStats.R",
  "ResultsAnalyze/SuperLModel_GenScalingResults.R"
)

stage_names <- gsub("[^A-Za-z0-9]+", "_", sub("\\.R$", "", runtime_files))

con <- file(output_path, open = "w", encoding = "UTF-8")
on.exit(close(con), add = TRUE)

writeLines("# Code generated by tools/generate_runtime_registry.R; do not edit by hand.", con = con)
writeLines("", con = con)
writeLines(".ndm_eval_runtime_stage_expr <- function(expr, env) {", con = con)
writeLines("  stopifnot(is.environment(env))", con = con)
writeLines("  eval(expr, envir = env)", con = con)
writeLines("  invisible(env)", con = con)
writeLines("}", con = con)
writeLines("", con = con)

for (i in seq_along(runtime_files)) {
  write_expression_assignment(
    con = con,
    name = sprintf(".ndm_stage_expr_%s", stage_names[[i]]),
    path = file.path(runtime_root, runtime_files[[i]])
  )
}

writeLines(".ndm_runtime_stage_registry <- local({", con = con)
writeLines("  list(", con = con)
for (i in seq_along(runtime_files)) {
  comma <- if (i < length(runtime_files)) "," else ""
  writeLines(
    sprintf(
      "    %s = function(env) .ndm_eval_runtime_stage_expr(.ndm_stage_expr_%s, env)%s",
      encodeString(runtime_files[[i]], quote = "\""),
      stage_names[[i]],
      comma
    ),
    con = con
  )
}
writeLines("  )", con = con)
writeLines("})", con = con)
writeLines("", con = con)

write_expression_assignment(con = con, name = ".ndm_run_impl_expr", path = run_api_path)
write_expression_assignment(con = con, name = ".ndm_multidisease_driver_expr", path = multidisease_driver_path)

writeLines(".ndm_new_run_impl_env <- function() {", con = con)
writeLines("  env <- new.env(parent = baseenv())", con = con)
writeLines("  eval(.ndm_run_impl_expr, envir = env)", con = con)
writeLines("  env", con = con)
writeLines("}", con = con)
writeLines("", con = con)

writeLines(".ndm_eval_multidisease_driver <- function(env) {", con = con)
writeLines("  .ndm_eval_runtime_stage_expr(.ndm_multidisease_driver_expr, env)", con = con)
writeLines("}", con = con)
